server:
  port: 9999
spring:
  application:
    name: zuul-service
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka/
# 高可用Eureka配置示例
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
#  instance:
#    prefer-ip-address: true

zuul:
  routes:
    my-route-name: # 路由的名称，可以随便命名
      path: /ms-goods/**  # 路由的访问地址
      serviceId: GOODS-SERVICE  # 路由到的微服务的名称

management:
  endpoints:
    web:
      exposure:
        include: "*"
